version: '3.8'

services:
  mydatabase:
    image: postgres:11.22-alpine3.18
    environment:
      POSTGRES_DB: hopperplus
      POSTGRES_PASSWORD: ESSKEETIT1
      POSTGRES_USER: postgres
    volumes:
      - pg_pi_grasshopper_data:/var/lib/postgresql/data
    networks:
      - grasshopperpi_net

  mybackend:
    depends_on:
      - mydatabase
    image: grasshopperpi:v1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8083:8083"
    networks:
      - grasshopperpi_net

volumes:
  pg_pi_grasshopper_data:
    external: false

networks:
  grasshopperpi_net:
    external: false

secrets:
  db_dev_pass:
    external: true  